version: '3.7'

services:
  mysql8:
    env_file:
      - .env
    image: mysql:8.0.22
    container_name: mysql8_container
    restart: always
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command:
      [
        '--sort-buffer-size=2097152',
        '--read_rnd_buffer_size=2097152',
        '--innodb-dedicated-server=ON',
        '--default-authentication-plugin=mysql_native_password'
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql8_data:/var/lib/mysql

  phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql8_container
      # PMA_ARBITRARY: 1
      #PMA_USER: root
      #PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - mysql8

volumes:
  mysql8_data:

networks:
  default:
